# Generated by Django 4.2.4 on 2023-08-10 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_rename_group_pupil_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.BigIntegerField()),
                ('month', models.DateField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.group')),
                ('pupil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.pupil')),
            ],
        ),
    ]
