# Generated by Django 4.2.4 on 2023-08-10 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='month',
            new_name='date',
        ),
    ]
