# Generated by Django 4.2.4 on 2023-08-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_payment_amount_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='API.group'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pupil',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='API.pupil'),
        ),
    ]
